{% set name = "wasabi" %}
{% set version = "0.4.1" %}
{% set sha256sum = "440be2c40f1e2ee5538c38b3cd86b779b718288fd8d153a67ee81b4af703c180" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
    requires:
        - pytest <4
    imports:
        - {{ name }}
    commands:
        - python -m pytest --tb=native --pyargs {{ name }}


about:
  home: http://github.com/ines/wasabi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A lightweight console printing and formatting toolkit'

  dev_url: https://github.com/ines/wasabi
  doc_url: https://github.com/ines/wasabi#-api

extra:
  recipe-maintainers:
    - ines
    - honnibal
