travis:
  secure:
    BINSTAR_TOKEN: jvjwB3ZufIiV/+YRztUraQNIjxbjV+j84OfCfdNXuYHvCmgQdvYG1KRRfyXfSx7HJYpp90jS8+YnwGWsi00v603nM3ciVDdBQOhNyBI+tKUCntD1iVnOxxwn2na/KTUe4UyLJjJuSM8tTKlseCGeWHyb7r4O8vsyiUiKlnpr2sdWUnKdUJo75fWXbJUsnXe1tHN2CWdMhkTpwz3g0RaVzFBylt3dW4P+AypQkEfoSx6aiW4QGrBHoH8jMKFXZGjnNrvC+87B1oBcB1EMb/XyYVXI7gP96uVNR+mt0yJ0ORmek7gbZa3LO4nQzyIkB1IkM2RIKyfr+Qm3mSwup8LHhiOFo8ILlMC+6gAjZF58VSmSfQOtHnXXKiLLSxDgiyfRzewd8NfffreDZVND0N61/B/OD8rZoYZ2pb+YZdFkxS6jwc4dQL8dRdLS0FeXRmhb5dxwaDauMK6EHbOIHOIE5CqopBIH/aCcY4m5GYal4jxUhifJq2UICNl3tfwtlVYobUtMC96o/0zsNbWKMB8PRQ2dRTgXJZufMyR/pnPGfGqwJ4UL5hoMKkk5NofXtZx/mzK+iJqnKMRXs42X0nSPOE7xJT1CC+8LpW3BADloByV4OZT3wVd4OqjSnv+FWXin+FhL/nP0WE97fRnIjOw+F/bPw2fRPeFWGO0Nd8r7NAs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
